### ISSUE TITLE
support mongoid 4

### ISSUE THREAD

**Issue by chenghung** [ryanong/mongoid_spacial#36]
<code>
# backtrace

NameError: uninitialized constant Mongoid::Spacial::Document::ClassMethods::Mongo
    from /usr/local/rvm/gems/ruby-2.0.0-p247/gems/mongoid_spacial-0.2.13/lib/mongoid_spacial/spacial/document.rb:19:in `spacial_index'
    from /home/eddie/projects/zooti/app/models/provisioning_manager_server.rb:20:in`class:ProvisioningManagerServer'
    from /home/eddie/projects/zooti/app/models/provisioning_manager_server.rb:1:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-2.0.0-p247/gems/zeus-0.13.3/lib/zeus/load_tracking.rb:50:in`load'
    from /usr/local/rvm/gems/ruby-2.0.0-p247/gems/zeus-0.13.3/lib/zeus/load_tracking.rb:50:in `load'
    from (irb):1
    from /usr/local/rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.0/lib/rails/commands/console.rb:90:in`start'
    from /usr/local/rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.0/lib/rails/commands/console.rb:9:in `start'
    from /usr/local/rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.0/lib/rails/commands.rb:64:in`<top (required)>'
    from ./bin/rails:4:in `require'
    from ./bin/rails:4:in`<main>'

</code>

<code>
# my model

  spacial_index :location   # line 20

</code>

**Comment by vanboom** [comment]
Same here.

**Comment by ryanong** [comment]
use mongoid_spatial. This gem is no longer supported
